---
# tasks file for nodejs
- name: pre-install nodejs
  shell: |
    # Using Ubuntu
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

- name: install nodejs
  apt:
    name: nodejs
    state: latest