---
# tasks file for maven
- name: make directory
  become: false
  file:
    path: ~/tools/maven
    state: directory
  tags:
  - maven

- name: download maven
  become: false
  get_url:
      dest: ~/tools/maven # required. Absolute path of where to download the file to.,If C(dest) is a directory, either the server provided filename or, if none provided, the base name of the URL on the remote server will be used. If a directory, C(force) has no effect.,If C(dest) is a directory, the file will always be downloaded (regardless of the C(force) option), but replaced only if the contents changed..
      url: http://apachemirror.wuchna.com/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz # required. HTTP, HTTPS, or FTP URL in the form (http|https|ftp)://[user[:pass]]@host.domain[:port]/path
  tags:
  - maven

- name: unzip to location
  become: false
  unarchive:
    src: ~/tools/maven/apache-maven-3.6.3-bin.tar.gz
    dest: ~/tools/maven
  tags:
  - maven

- name: make soft link
  become: false
  file:
    src: ~/tools/maven/apache-maven-3.6.3
    dest: ~/tools/maven/current
    state: link
  tags:
  - maven

- name: add to path
  become: false
  lineinfile:
      path: ~/.zshrc 
      insertafter: EOF 
      backup: yes 
      line: "[[ ! -d ~/tools/maven/current ]] || PATH=$PATH:~/tools/maven/current/bin" 
  tags:
  - maven